server:
  port: ${PORT:8085}

spring:
  application:
    name: alert-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  level:
    org.apache.kafka: WARN
